apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: elclaustro-strapi
  labels:
    app: postgres-data
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-data
  namespace: elclaustro-strapi
  labels:
    app: discourse-data
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-data-log
  namespace: elclaustro-strapi
  labels:
    app: discourse-data-log
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
